//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;

public partial class dbEntities : DbContext
{
    public dbEntities()
        : base("name=dbEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<tbl> tbls { get; set; }
    public DbSet<tblbook> tblbooks { get; set; }

    public virtual ObjectResult<login_Result> login(string email, string pass)
    {
        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));

        var passParameter = pass != null ?
            new ObjectParameter("Pass", pass) :
            new ObjectParameter("Pass", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<login_Result>("login", emailParameter, passParameter);
    }

    public virtual ObjectResult<userdata_Result> userdata(Nullable<bool> status)
    {
        var statusParameter = status.HasValue ?
            new ObjectParameter("status", status) :
            new ObjectParameter("status", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userdata_Result>("userdata", statusParameter);
    }

    public virtual ObjectResult<userdata1_Result> userdata1(Nullable<bool> status)
    {
        var statusParameter = status.HasValue ?
            new ObjectParameter("status", status) :
            new ObjectParameter("status", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userdata1_Result>("userdata1", statusParameter);
    }

    public virtual ObjectResult<deleteuser_Result> deleteuser(Nullable<int> usrid)
    {
        var usridParameter = usrid.HasValue ?
            new ObjectParameter("usrid", usrid) :
            new ObjectParameter("usrid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<deleteuser_Result>("deleteuser", usridParameter);
    }

    public virtual int userdelete(Nullable<int> userid)
    {
        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("userdelete", useridParameter);
    }

    public virtual ObjectResult<bokdata_Result> bokdata(Nullable<bool> type)
    {
        var typeParameter = type.HasValue ?
            new ObjectParameter("type", type) :
            new ObjectParameter("type", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bokdata_Result>("bokdata", typeParameter);
    }
}
